# Generated by Django 4.2.3 on 2023-08-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
